### ISSUE TITLE
menu isnt opening when pressing "E"!

### ISSUE THREAD

**Issue by djowdobom** [Cheleber/weedz#1]
As the title explains, i just cant see the menu when pressing "E"

**Comment by b4b4s666** [comment]
Its work in progress repair the script or wait next pacth for my part i repaired it and added more plant but when i fertiliZe or add water its adding it to all plant at same time xD srill tryimg to fix this

**Comment by djowdobom** [comment]
oh, ok! Really appreciate the answer, thanks!

**Comment by b4b4s666** [comment]
Np

**Comment by Cheleber** [comment]
Fixed! Commit is going off now! Sorry for the late answer, troubles in life hehe
