### ISSUE TITLE
Dont see weed trees/plants

### ISSUE THREAD

**Issue by amakuu** [Cheleber/weedz#2]
AS in topic,
players didnt see weed trees/plants

**Comment by Cheleber** [comment]
You are doing something wrong in the db or some resources is conflicting with weedz.
Because when I try on my server the props do not disappear or they do not appear in any moment

**Comment by Cheleber** [comment]
Also make sure you are using weedz latest version!

SS's:
![image](https://user-images.githubusercontent.com/35751599/43324766-d91d988e-91ac-11e8-94e7-0f2da7fe0e8e.png)
![image](https://user-images.githubusercontent.com/35751599/43324808-f9605488-91ac-11e8-83a2-5e896c95e384.png)
![image](https://user-images.githubusercontent.com/35751599/43324919-30dda672-91ad-11e8-9ac4-d3e70d324721.png)

P.S: The pots are not available yet, is a test for the next version.

**Comment by amakuu** [comment]
okay, i'll check. btw. Very nice script 👍

**Comment by Cheleber** [comment]
Thanks mate!

Also try to start the resources by this order:

start weedz
start MenuWeedz
start vSync

But i think is some resource conflicting, try open a clean server with only the weedz script!

**Comment by arnexuhc** [comment]
The samme is happening for me i can se you dont have start NativeUI But my start is looking like this

start weedz
start vSync
start NativeUI
start MenuWeedz

is that right or worng

**Comment by Cheleber** [comment]
Yes, is right!
NativeUI have to be first in relation to the menu...

The problem is with some resource, you tried what i said?

 try open a clean server with only the weedz script!

**Comment by arnexuhc** [comment]
But then i dont have my Addons

**Comment by Cheleber** [comment]
Just for testing, some resource in your server is conflicting with weedz

**Comment by arnexuhc** [comment]
but how along time do there go to next update
